### ISSUE TITLE
Friend tracking doesn't work

### ISSUE THREAD

**Issue by ColdLemur** [rhunk/SnapEnhance#1060]
### Description

Friend tracking doesn't work, I had it set up the exact same way as admins and I don't get notifications or logs. I've followed their advice of clearing app data and it didn't help
![Screenshot_20240522-011141](https://github.com/rhunk/SnapEnhance/assets/164411733/2a3d8761-19dd-4738-9bff-6734cd9cd877)
![Screenshot_20240522-011245](https://github.com/rhunk/SnapEnhance/assets/164411733/2feb1789-612b-4fd2-8318-704cfb7f27a2)

### Reproduction steps
[Admins Guide](https://github.com/bocajthomas/SnapEnhance/blob/wiki/FriendTrackerExplained.md)

### Snapchat Version

12.79.0.37

### SnapEnhance Version

2.1.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@ColdLemur could you export your logs & config and then send
